### ISSUE TITLE
Annotations for 3DPW-OC/PC

### ISSUE THREAD

**Issue by RammusLeo** [YangChangHee/ICCV2023_SEFD_RELEASE#4]
Hi! An exciting work!
Would you mind provide your annotations for 3DPW-OCC and 3DPW-PC datasets so that I can reproduce your results? By the way, the link to 3DPW datasets [3DPW](https://drive.google.com/drive/folders/1pT0Ix3FxieEQf0HhEbMN1o-DWRzw2Ugh?usp=sharing) returns 404 not found.
I'm looking forward to your reply!

**Comment by YangChangHee** [comment]
Hello! Thank you for your interest in our research! 
First, for the results of 3DPW-OCC, we referred to the following link: https://github.com/chhankyao/visdb/blob/main/data/PW3D/PW3D.py. And for the results of 3DPW-PC, 
we referred to the ROMP paper! Please check it out. 
Finally, we obtained the 3DPW dataset from https://virtualhumans.mpi-inf.mpg.de/3DPW/. 
Could you confirm the exact URL address? We are unsure if it refers to our SMPL edge dataset or something else :)

**Comment by RammusLeo** [comment]
Thanks very much! I think some 'DATA' URLs in your [directory.md](https://github.com/YangChangHee/ICCV2023_SEFD_RELEASE/blob/main/assets/directory.md) goes to 404, not only 3DPW. Maybe the original address has been abandoned? If it is convenient you can have a check :)

**Comment by YangChangHee** [comment]
Thank you! We used 3DCrowdNet as a baseline, and followed the dataset format of this model. 
However, it seems that the dataset URL for I2L-MeshNet has changed, which 3DCrowdNet now follows. So, I updated it to the correct URL, and if you check now, you should be able to access it! Thanks for fixing the mistake! :) 
If there are any other issues, let me know right away! 
I feel like the code is written too raw, so there might be many problems! 
(Finally, if the issue is resolved, please close it!)

**Comment by RammusLeo** [comment]
All right! Thanks for your quick reply!
