### ISSUE TITLE
No Edge module and Distillation module files

### ISSUE THREAD

**Issue by ocissor** [YangChangHee/ICCV2023_SEFD_RELEASE#6]
Hi, Can you please share the _**checkpoint_epoch64.pth**_ and **_smpl_overlap.pth.tar_**. Also can you please share the teacher model architecture details like the structure of the Regressor and Feature Encoder, I could not find that in the paper.

Thank you!

**Comment by YangChangHee** [comment]
"Hello!
First of all, thank you so much for your keen interest in our research! :)
Firstly, regarding the checkpoint file 'checkpoin_epoch64.pth,' it is the checkpoint file for the SMPL Edge Estimator (SEE). The network backbone in this case uses the UNet Backbone, and if you look at the Model.py file, you can see that it calls the UNet class for utilization!
Secondly, for 'SMPL_overlap.pth,' you can consider it as the Teacher Model. It is a checkpoint file obtained through our direct training, and it is uploaded for the sake of convenience and to provide it to you!
Thirdly, for details on the Model Architecture, we used 3DCrowdNet as our baseline, and for a more in-depth understanding, we would appreciate it if you could refer to the 3DCrowdNet paper :). Additionally, we have verified the effectiveness of our approach when applied to a bottom-up approach like BEV and observed its functionality in a top-down approach such as I2L-MeshNet! This implies that our method is indeed very powerful!
Finally, the Teacher Model in its trained state (SMPL_overlap.pth) only utilizes the Encoder part without using the regressor section! (It is used only for training purposes, and the teacher encoder is not used during testing or inference!)
Additionally, to estimate the SMPL edge, we designed two networks (SEE, SESD), and this information is provided in the Supplementary. However, I tried to find our supplementary on the website but had difficulty locating it. Therefore, I will upload it separately on GitHub :) (As I am currently on a business trip, it may take a little time. Thank you for your understanding.)
I am sharing the paper URLs used for 3DCrowdNet, UNet, and SESD :)
If it has been helpful, giving us a GitHub star would be greatly appreciated and empowering for us.
[3DCrowdNet](https://github.com/hongsukchoi/3DCrowdNet_RELEASE)
[UNet](https://github.com/milesial/Pytorch-UNet)
[Self-Supervised Sence De-Occlusion](https://openaccess.thecvf.com/content_CVPR_2020/papers/Zhan_Self-Supervised_Scene_De-Occlusion_CVPR_2020_paper.pdf)

**Comment by ocissor** [comment]
hi, thank you for your response. There are two files for the models one is Model.py and the other is Model copy.py.  If my understanding is correct to train the **teacher model** and then use the trained teacher model to train my **student model** I use the Model copy.py file(where first I train with SMPL_overlap_edges set to True and get my trained Teacher model, and to train my student model I set distillation_pretrained=True and pass the path of the trained Teacher model). Can you please tell if my understanding is correct?

Thank you!!

**Comment by YangChangHee** [comment]
Firstly, 'Model.py' is a file intended for training and testing SEFD (Structural Edge Feature Distillation). In other words, it is designed to work specifically with Canny edge detection. On the other hand, 'Model copy.py' is a file where various structural maps such as HED, PiDiNet, EPS, segmentation, etc., were implemented. Both of these files are expected to function well for SEFD training. The reason for dividing them into two files is due to the code refactoring process. However, complications arose during the refactoring of code for different structural maps due to various errors, leading to a temporary postponement of that aspect.

Therefore, any 'model.py' can be used for SEFD training, and ongoing efforts for refactoring the code for various structural maps are continuing, with updates expected soon! Regarding 'SMPL_overlap_edges,' you are correct in your understanding!! :)

If all the issues have been resolved, please close issue!
