### ISSUE TITLE
What are SMPL_overlap_edge1 and SMPL_overlap_edge2 folders under 3dpw folder.

### ISSUE THREAD

**Issue by ocissor** [YangChangHee/ICCV2023_SEFD_RELEASE#9]
Hi, I was going through the code to make SMPL_overlap_edges for the 3dpw dataset(file - make_3DPW_smpl_edge.py) here I don't see you making any folders named SMPL_overlap_edge1 or SMPL_overlap_edge2. You are making two folders named SMPL_overlap_edge and SMPL_all_edge, but in the PW3D.py I see you are accessing the folders SMPL_overlap_edge1 and SMPL_overlap_edge2, can you explain what are these two folders for and how to put correct files in these two folders while running -  make_3DPW_smpl_edge.py

Thank you!!

**Comment by YangChangHee** [comment]
I apologize for contacting you late. 
I have just confirmed it now due to my graduation schedule. 
To match the folders, please rename 'SMPL_overlap_edge2' to 'SMPL_overlap_edge.' For 'SMPL_all_edge,' consider it as 'I_dilation_edge' in Table 2 of the paper. The visual results can be found in Figure 7 (h). 
Thank you. :)

**Comment by ocissor** [comment]
Thank you!
